@startuml usecase-auth
left to right direction
actor Guest
actor Client
actor Expert
actor Admin

rectangle Authentication {
  usecase "Register" as UC1
  usecase "Login" as UC2
  usecase "Logout" as UC3
}

Guest --> UC1
Guest --> UC2
Client --> UC3
Expert --> UC3
Admin --> UC3
@enduml
